version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "refactor/rework-arch"
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "refactor/rework-arch"
    commit-message:
      prefix: "deps: "
    groups:
      pip-dependencies:
        patterns:
          - "*"
