"""Module which contains all available mixture classifier criterions for mixture classifiers"""

__author__ = "Mark Dubrovchenko"
__copyright__ = "Copyright (c) 2025 PySATL project"
__license__ = "SPDX-License-Identifier: MIT"

from pysatl_mpest.preprocessing.components_family.criterions.abstract_criterion import (
    AHistClassifierCriterion,
    APeaksClassifierCriterion,
    ASampleClassifierCriterion,
)
from pysatl_mpest.preprocessing.components_family.criterions.frequency_criterions import (
    CDct,
    CDctEnergy,
    CSpecBandwidth,
    CSpecCentroid,
    CSpecDecrease,
    CSpecEnergy,
    CSpecEntropy,
    CSpecFlatness,
    CSpecRolloff,
    CSpecSlope,
    CWaveletEnergy,
    CWaveletEntropy,
    CWaveletLarge,
    CWaveletMean,
    CWaveletStd,
)
from pysatl_mpest.preprocessing.components_family.criterions.hist_criterions import (
    CHistEnergy,
    CHistEntropy,
    CHistFlat,
    CHistLength,
    CHistUniform,
    CSobelCount,
    CSobelMax,
    CSobelMean,
    CSobelMin,
)
from pysatl_mpest.preprocessing.components_family.criterions.peaks_criterions import (
    CPeaksCount,
    CPeaksDistMax,
    CPeaksDistMean,
    CPeaksDistMin,
    CPeaksFirst,
    CPeaksLast,
    CPeaksMax,
    CPeaksMean,
    CPeaksMin,
    CPeaksWidthMax,
    CPeaksWidthMean,
    CPeaksWidthMin,
    CValleysDistMax,
    CValleysDistMean,
    CValleysDistMin,
    CValleysMax,
    CValleysMean,
    CValleysMin,
    CValleysWidthMax,
    CValleysWidthMean,
    CValleysWidthMin,
)
from pysatl_mpest.preprocessing.components_family.criterions.sample_criterions import (
    CBootKurt,
    CHillAbs,
    CIqr,
    CKurt,
    CKurtMoors,
    CLogRatio,
    CMaxZscore,
    CNegativeValue,
    COutlierFraction,
    CRange,
    CSkew,
    CSkewBowley,
    CSpacingGap,
    CSpacingGini,
)

base_criterions: list[ASampleClassifierCriterion | APeaksClassifierCriterion | AHistClassifierCriterion] = [
    CIqr(),
    CKurt(),
    CSkew(),
    CNegativeValue(),
    CRange(),
    CMaxZscore(),
    CPeaksCount(),
    CPeaksMean(),
    CValleysMean(),
    CPeaksMax(),
    CPeaksMin(),
    CPeaksWidthMax(),
    CPeaksWidthMin(),
    CPeaksWidthMean(),
    CPeaksDistMax(),
    CPeaksDistMin(),
    CPeaksDistMean(),
    CValleysMax(),
    CValleysMin(),
    CValleysWidthMax(),
    CValleysWidthMin(),
    CValleysWidthMean(),
    CValleysDistMax(),
    CValleysDistMin(),
    CValleysDistMean(),
    CHistEnergy(),
    CHistEntropy(),
    CHistLength(),
    CHistUniform(),
    CSpecEnergy(),
    CSpecCentroid(),
    CSpecSlope(),
    CSpecRolloff(),
    CSpecBandwidth(),
    CSpecFlatness(),
    CSpecEntropy(),
    CSpecDecrease(),
    CDct(1),
    CDct(2),
    CDct(3),
    CDctEnergy(),
    CPeaksFirst(),
    CPeaksLast(),
    CBootKurt(),
    CHillAbs(),
    CSkewBowley(),
    CKurtMoors(),
    CLogRatio(),
    CHistFlat(),
    COutlierFraction(),
    CSpacingGap(),
    CSpacingGini(),
    CSobelCount(),
    CSobelMean(),
    CSobelMax(),
    CSobelMin(),
    CWaveletEnergy(1),
    CWaveletEnergy(2),
    CWaveletEnergy(3),
    CWaveletEntropy(1),
    CWaveletEntropy(2),
    CWaveletEntropy(3),
    CWaveletMean(1),
    CWaveletMean(2),
    CWaveletMean(3),
    CWaveletStd(1),
    CWaveletStd(2),
    CWaveletStd(3),
    CWaveletLarge(1),
    CWaveletLarge(2),
    CWaveletLarge(3),
    CWaveletLarge(1, 0.01),
    CWaveletLarge(2, 0.01),
    CWaveletLarge(3, 0.01),
]
